import React from "react";
import type { Metadata } from "next";
import {Noto_Serif} from "next/font/google";
import "./globals.css";
import RootContainer from "@/layouts/RootContainer/RootContainer";
import ThemeProvider from "@/layouts/ThemeProvider";
import DialogProvider from "@/layouts/DialogProvider";
import BlurLayer from "@/layouts/BlurLayer/BlurLayer";

const inter = Noto_Serif({
  subsets: ["latin"],
  weight: "400",
});


export const metadata: Metadata = {
  title: "book",
  description: "Generated by create next app",
  icons: {
    icon:
      [
        {
          rel: 'icon',
          url: "/svg/favicon-black.svg",
          media: "(prefers-color-scheme: light)",
        },
        {
          rel: 'icon',
          url: "/svg/favicon-white.svg",
          media: "(prefers-color-scheme: dark)",
        }
      ],

  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={inter.className}>
    <ThemeProvider>
      <DialogProvider>
        <BlurLayer/>
        <RootContainer>
          {children}
        </RootContainer>
      </DialogProvider>
    </ThemeProvider>
    </body>
    </html>
  );
}
